### PR TITLE
Fix: navigation issue after interview save

### PR DESCRIPTION
**Pull request by Abhishek01039**
In the `go_router`, `popUntil` and `pushNamePopUntil` methods haven't been implemented yet by the google team. that's why we have use navigator.pop in for loop

### CODE REVIEW

**Comment by orioli** [comment]
@Abhishek01039  The issue remains unsolved, after saving an interview I am redirected out of the project folder!

**Comment by Abhishek01039** [comment]
This fix is about this issue https://github.com/QualNotes-AB/qualnotes/issues/40

**Comment by Abhishek01039** [comment]
@orioli I am working on redirection stuff...

**Comment by orioli** [comment]
now it works. :)

**Pull request merged**
