### PR TITLE
Fix: routing issue after storing project

### PR DESCRIPTION
**Pull request by Abhishek01039**

### CODE REVIEW

**Review by orioli — COMMENTED** [review]
coded crashes when I open tab stepper and pdfs consent forms are already laoded.

**Comment by orioli** [comment]
@Abhishek01039  you have fixed somethign but broken somethign else, now when  I save a schedule, it does not save the questions. this happens after saving 2 schedules. :( can you check that?

**Comment by Abhishek01039** [comment]
ok, let me check!

**Comment by orioli** [comment]
@Abhishek01039 can you check this mega bug? https://www.youtube.com/watch?v=sZXZp4-FK_w

**Comment by orioli** [comment]
Fixed, however when I save interview I am redirected to ouside the project (instead to the tab page of the project) :(  can you fix @Abhishek01039

**Comment by Abhishek01039** [comment]
As far as I know, you want it to be like this only @orioli but let me fix this

**Pull request merged**
